name: Automated Tests for MultiVault

on:
  push:
    branches:
      - main
      - releases
  pull_request:
    branches:
      - main
      - releases

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        working-directory: ./multivault
        run: |
          npm install
          npm install --save-dev jest

      - name: Run Jest Tests
        working-directory: ./multivault
        run: npm test

  cypress-tests:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        working-directory: ./multivault
        run: |
          npm install
          npm install --save-dev cypress

      - name: Run Cypress Tests
        working-directory: ./multivault
        run: npx cypress run

  enforce-tests-on-main:
    runs-on: ubuntu-latest
    needs: [test, cypress-tests]  # Add cypress-tests as a dependency

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        working-directory: ./multivault
        run: npm install

      - name: Run Jest Tests for Main
        working-directory: ./multivault
        run: npm test
