name: Automated Tests for MultiVault

on:
  push:
    branches:
      - main
      - releases
      - e2e 
  pull_request:
    branches:
      - main
      - releases
      - e2e  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        working-directory: ./multivault
        run: |
          npm install
          npm install --save-dev jest

      - name: Run Jest Tests
        working-directory: ./multivault
        run: npm test

  e2e-test:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        working-directory: ./multivault
        run: npm install

      - name: Run E2E Tests
        working-directory: ./multivault
        run: npm run test:e2e
